language: csharp
solution: Unosquare.Tubular.sln
notifications:
  slack: unolabs:cbusXPH6pBwZ35rVDzi4k4ve
dotnet: 2.0.0
mono: latest
sudo: required
install:
  - dotnet restore
script:
  - dotnet test ./test/Unosquare.Tubular.Tests/Unosquare.Tubular.Tests.csproj -f netcoreapp2.0
